### ISSUE TITLE
Preserve player direction even if player stops

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/O21#129]
Currently, we determine `Player.Direction` by the player velocity, and if the velocity is zero, then it defaults to `Right`.

We should preserve the last direction when the player stops.

See `TODO[#xxx]` in the code.

**Comment by Fantoom** [comment]
What about mutable field with previous direction value in Player type?

**Comment by ForNeVeR** [comment]
No mutable fields, the whole game engine should be immutable.
