### ISSUE TITLE
Music stops during resize

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/O21#137]
Can we make it still play during game window resize?

**Comment by Evgeny608799** [comment]
This issue linked with original `Raylib library`. Is doesent support drawing during resize or move window (Event processing (PollEvents) stalls whenever the window is resized). It would be possible to solve this problem, but current version of `Raylib_CsLo` does not support risize callback. [Issue](https://github.com/raysan5/raylib/issues/1680)

**Comment by ForNeVeR** [comment]
I wonder if we could start playing music in a separate thread (or even dispatcher) then.
