### ISSUE TITLE
Screen width and height config

### ISSUE THREAD

**Issue by Fantoom** [ForNeVeR/O21#139]
I think that we need a way to set screen width and height. We can do it as command line argument (--width and --height)

**Comment by ForNeVeR** [comment]
I am not against that, but why would we need that, provided the screen is resizeable?

**Comment by Fantoom** [comment]
By default it is 1200x800 and when I start it, the window edges are out of my screen. I can not resize it :)

**Comment by ForNeVeR** [comment]
1. I imagine you still can use hotkeys to control the window size. In Windows, `Win+Arrows` should make it manageable.
2. Maybe we should better choose a default instead of (or together with) adding a command-line option.

**Comment by Fantoom** [comment]
1) I will try it, but I think, that many people do not know about it
2) What default value do you suggest?

**Comment by ForNeVeR** [comment]
2. `max theSizeWeWant userScreenSize`

**Comment by Fantoom** [comment]
Ok, `Win+Arrows` helped me, but I still think, that we should provide some way for that

**Comment by Fantoom** [comment]
> 2. `max theSizeWeWant userScreenSize`

What these values are? Is `userScreenSize` the acutal size of user's screen or the size user provided (as argument or whatever). And what value for `theSizeWeWant` do we want? A predefined constant?

**Comment by ForNeVeR** [comment]
`theSizeWeWant` is the default, 1200×1600 or whatever.
`userScreenSize` is the actual size of the screen we'll show our window on, we should investigate how to get that on Raylib's windowing system.

**Comment by ForNeVeR** [comment]
For `userScreenSize`, see Raylib's `GetMonitorWidth(int)` and such.

**Comment by Fantoom** [comment]
> max theSizeWeWant userScreenSize

are you sure that we want the max? If the user has a lower resolution, the window will go out of the screen bounds

**Comment by ForNeVeR** [comment]
Ah, yeah, we want `min` actually, sorry for the confusion.

**Comment by Fantoom** [comment]
and what about `GetScreenWidth(void)` and `GetScreenHeight(void)`?

**Comment by ForNeVeR** [comment]
This is dubious: which screen do they use? Will it be the screen the game window is on?

**Comment by Fantoom** [comment]
https://www.raylib.com/cheatsheet/cheatsheet.html
`//Get current screen width`

**Comment by ForNeVeR** [comment]
"The current screen" is not a very definitive term, is it?

**Comment by Fantoom** [comment]
Is `int GetCurrentMonitor(void); // Get current connected monitor` more definitive? I don't think so :)

**Comment by ForNeVeR** [comment]
Of course it is! It literally _gives a definition_ for what is "the current monitor". It is the one returned by `GetCurrentMonitor`. Which we can read the sources to know more 😅

**Comment by Fantoom** [comment]
I have read sources, and found out that `GetScreenWidth` returns `CORE.Window.screen.width` which is the width of `used render area`. So we need `used render area`
