### ISSUE TITLE
Async level initialization

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/O21#47]
Currently, we have synchronous level init.

We should make that async, probably.

See `TODO[#47]` in the code (#40).

**Comment by ettud** [comment]
`TODO[#47]` is no longer available and the code has changed. We have `let! level = Level.Load directory 1 2` during the game initialization. Do you suggest to make it a delayed async computation?

**Comment by ForNeVeR** [comment]
1. Anything that does network or disk IO should be asynchronous.
2. Please wait for #60, that PR introduces a lot of async activities for content loading. There's no async execution mechanism for in-game mode, but we may discuss that after the PR is merged. I imagine something similar to the `LoadingLoop` (https://github.com/ForNeVeR/O21/blob/cc5c046af966cb09cddbcad6986efc63b42d378b/O21.Game/Loading/LoadingLoop.fs) in the main game.

**Comment by ForNeVeR** [comment]
I think that the level initialization is already async right now.

When adding new level support, we'll load them all at once (that's just easier and shouldn't be a problem with our level count and memory requirements).
