### ISSUE TITLE
Decoding Cyrillic characters in path

### ISSUE THREAD

**Issue by sotiredofyours** [ForNeVeR/O21#92]
The problem is that if there are Cyrillic characters in the path to the working folder, then the path to the folder with fonts will be incorrectly decoded. As a result, fonts will not be loaded.

Example:

Path: `D:/<cyrillic symbols>/O21/../`
![image](https://github.com/ForNeVeR/O21/assets/81583669/a8437c94-dd8c-4257-90f4-0b63c61e6f30)

**Comment by ForNeVeR** [comment]
I guess that's a problem of RayLib that's using single-byte encoding on Windows (which is _never_ the right choice).

A fix would be to read the files ourselves and then load the fonts from the read data.
